version: '3.8'

services:

  my-rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1

  server:
    build: server
    volumes:
      - ./server:/app
    restart: on-failure
    depends_on: 
      - my-rabbitmq
    ports:
      - 5000:5000
    environment: # send python output straight to terminal
      - PYTHONUNBUFFERED=1
